title: notifine - Reliable Telegram notifications for Github and Gitlab
description: Instant Github, Gitlab notifications for Telegram
show_downloads: false
google_analytics:
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
